#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created logs will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /test-inside/test /test-logs/' EXIT

#must import public key
# rpm --import /tmp/public.asc

yum -y install /out/*.rpm

# not exactly sure what makes a good test here
# perhaps include test files in the repo and run dssp
mkdssp -i /test-inside/files/pdb3cgz.ent -o /tmp/pdb3cgz.actual
DATE="$(date +'%Y-%m-%d')"
sed -e "s/2016-07-07/$DATE/" < /test-inside/files/pdb3cgz.out > /tmp/pdb3cgz.expected
DIFF="$(diff /tmp/pdb3cgz.actual /tmp/pdb3cgz.expected)"
rm /tmp/pdb3cgz.actual /tmp/pdb3cgz.expected
if [ ! -z "$DIFF" ]; then
    echo $PATH
    return 1
fi
